"""
Base Strategy for Polymarket Trading Bot.
Provides framework for implementing trading strategies.
"""

import asyncio
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Awaitable, Callable, Optional

from config.settings import settings
from inventory.manager import InventoryManager
from models.data_models import Market, OrderbookSnapshot, Side, TokenType

logger = logging.getLogger(__name__)


class SignalType(str, Enum):
    """Trading signal types."""

    BUY_YES = "BUY_YES"
    BUY_NO = "BUY_NO"
    SELL_YES = "SELL_YES"
    SELL_NO = "SELL_NO"
    MERGE = "MERGE"
    NO_ACTION = "NO_ACTION"


@dataclass
class TradingSignal:
    """Trading signal generated by strategy."""

    signal_type: SignalType
    market_id: str
    token_id: str
    token_type: TokenType
    price: float
    size: float
    urgency: float = 0.5  # 0-1, higher = more urgent
    reason: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def side(self) -> Optional[Side]:
        if self.signal_type in [SignalType.BUY_YES, SignalType.BUY_NO]:
            return Side.BUY
        elif self.signal_type in [SignalType.SELL_YES, SignalType.SELL_NO]:
            return Side.SELL
        return None


@dataclass
class MarketState:
    """Current state of a market for strategy analysis."""

    market: Market
    yes_orderbook: Optional[OrderbookSnapshot] = None
    no_orderbook: Optional[OrderbookSnapshot] = None
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def yes_best_bid(self) -> Optional[float]:
        if self.yes_orderbook and self.yes_orderbook.best_bid:
            return self.yes_orderbook.best_bid.price
        return None

    @property
    def yes_best_ask(self) -> Optional[float]:
        if self.yes_orderbook and self.yes_orderbook.best_ask:
            return self.yes_orderbook.best_ask.price
        return None

    @property
    def no_best_bid(self) -> Optional[float]:
        if self.no_orderbook and self.no_orderbook.best_bid:
            return self.no_orderbook.best_bid.price
        return None

    @property
    def no_best_ask(self) -> Optional[float]:
        if self.no_orderbook and self.no_orderbook.best_ask:
            return self.no_orderbook.best_ask.price
        return None

    @property
    def combined_ask_price(self) -> Optional[float]:
        """Cost to buy both YES and NO at best asks."""
        if self.yes_best_ask is not None and self.no_best_ask is not None:
            return self.yes_best_ask + self.no_best_ask
        return None

    @property
    def combined_bid_price(self) -> Optional[float]:
        """Value if selling both YES and NO at best bids."""
        if self.yes_best_bid is not None and self.no_best_bid is not None:
            return self.yes_best_bid + self.no_best_bid
        return None

    @property
    def time_to_expiry(self) -> timedelta:
        """Time remaining until market ends."""
        return self.market.end_date_iso - datetime.utcnow()

    @property
    def seconds_to_expiry(self) -> float:
        """Seconds until market ends."""
        return self.time_to_expiry.total_seconds()

    @property
    def is_expired(self) -> bool:
        """Check if market has expired."""
        return self.seconds_to_expiry <= 0


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.

    Subclasses must implement:
    - analyze(): Analyze market state and generate signals
    - should_trade(): Determine if trading conditions are met
    """

    def __init__(self, inventory: InventoryManager, name: str = "BaseStrategy"):
        self.inventory = inventory
        self.name = name

        # Strategy parameters from config
        self.min_trade_size = settings.trading.min_trade_size
        self.max_trade_size = settings.trading.max_trade_size
        self.max_position_size = settings.trading.max_position_size
        self.orderbook_depth_levels = settings.trading.orderbook_depth_levels
        self.min_orderbook_depth = settings.trading.min_orderbook_depth
        self.min_profit_threshold = settings.trading.min_profit_threshold
        self.max_cost_basis = settings.trading.max_cost_basis
        self.min_time_to_expiry = settings.trading.min_time_to_expiry_seconds
        self.max_imbalance_ratio = settings.trading.max_imbalance_ratio

        # State tracking
        self._active_markets: dict[str, MarketState] = {}
        self._running = False

        # Callbacks
        self._on_signal: Optional[Callable[[TradingSignal], Awaitable[None]]] = None

    def on_signal(self, callback: Callable[[TradingSignal], Awaitable[None]]):
        """Register callback for trading signals."""
        self._on_signal = callback
        return callback

    @abstractmethod
    async def analyze(self, state: MarketState) -> list[TradingSignal]:
        """
        Analyze market state and generate trading signals.

        Args:
            state: Current market state with orderbook data

        Returns:
            List of trading signals (can be empty)
        """
        pass

    @abstractmethod
    def should_trade(self, state: MarketState) -> bool:
        """
        Check if general trading conditions are met.

        Args:
            state: Current market state

        Returns:
            True if trading is allowed
        """
        pass

    def update_market_state(
        self,
        market: Market,
        yes_orderbook: Optional[OrderbookSnapshot] = None,
        no_orderbook: Optional[OrderbookSnapshot] = None,
    ):
        """Update market state with new data."""
        state = MarketState(
            market=market,
            yes_orderbook=yes_orderbook,
            no_orderbook=no_orderbook,
            timestamp=datetime.utcnow(),
        )
        self._active_markets[market.condition_id] = state
        return state

    def get_market_state(self, market_id: str) -> Optional[MarketState]:
        """Get current state for a market."""
        return self._active_markets.get(market_id)

    async def process_orderbook_update(
        self,
        market: Market,
        orderbook: OrderbookSnapshot,
        token_type: TokenType,
    ):
        """
        Process orderbook update and potentially generate signals.

        This is called whenever we receive new orderbook data.
        """
        state = self._active_markets.get(market.condition_id)

        if state is None:
            state = MarketState(market=market)

        # Update the appropriate orderbook
        if token_type == TokenType.YES:
            state.yes_orderbook = orderbook
        else:
            state.no_orderbook = orderbook

        state.timestamp = datetime.utcnow()
        self._active_markets[market.condition_id] = state

        # Only analyze if we have both orderbooks
        if state.yes_orderbook and state.no_orderbook:
            if self.should_trade(state):
                signals = await self.analyze(state)

                for signal in signals:
                    if self._on_signal:
                        await self._on_signal(signal)

    def check_orderbook_depth(
        self,
        orderbook: OrderbookSnapshot,
        n_levels: int = 5,
    ) -> bool:
        """
        Check if orderbook has sufficient depth.

        Returns True if depth is adequate for trading.
        """
        n_levels = n_levels or self.orderbook_depth_levels
        bid_depth, ask_depth = orderbook.depth_at_levels(n_levels)

        return (
            bid_depth >= self.min_orderbook_depth
            and ask_depth >= self.min_orderbook_depth
        )

    def calculate_trade_size(
        self,
        available_size: float,
        desired_size: float,
        current_position: float = 0,
    ) -> float:
        """
        Calculate appropriate trade size given constraints.

        Args:
            available_size: Size available at the price level
            desired_size: Desired trade size
            current_position: Current position size

        Returns:
            Appropriate trade size
        """
        # Respect minimum trade size
        if desired_size < self.min_trade_size:
            return 0

        # Respect maximum trade size
        size = min(desired_size, self.max_trade_size)

        # Don't exceed available liquidity
        size = min(size, available_size)

        # Don't exceed max position
        remaining_capacity = self.max_position_size - current_position
        size = min(size, remaining_capacity)

        return max(0, size)

    def get_position_imbalance(self, market_id: str) -> float:
        """Get current position imbalance for a market."""
        position = self.inventory.get_market_position(market_id)
        if position:
            return position.imbalance_ratio
        return 0.0

    def stop(self):
        """Stop the strategy."""
        self._running = False
        self._active_markets.clear()
